### ISSUE TITLE
Problemas no pacote

### ISSUE THREAD

**Issue by andebana1** [willderazevedo/febranban-bancos#8]
O endereço consultado (https://www.febraban.org.br/associados/utilitarios/bancos.asp) está indisponível.

**Comment by willderazevedo** [comment]
O febraban mudou sua politica de consulta, tentarei mudar a função da consulta e caso não funcione terei que descontinuar o plugin. O plugin esta livre para receber PRs com soluções

**Comment by willderazevedo** [comment]
A nova página feita Angular encontra-se na URL: [https://portal.febraban.org.br/pagina/3164/12/pt-br/associados](Portal Febraban - Associados), não consegui fazer o GET com a tabela renderizada. No momento irei descontinuar o pacote, caso alguém consiga enviar um PR ficarei agradecido.

**Comment by guibranco** [comment]
https://github.com/guibranco/BancosBrasileiros
